// <auto-generated />
using Hotel.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Hotel.models.Chambre", b =>
                {
                    b.Property<int>("NumeroChambre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NumeroChambre"));

                    b.Property<int>("NombreLit")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("Tarrif")
                        .HasColumnType("float");

                    b.HasKey("NumeroChambre");

                    b.ToTable("Chambres");
                });

            modelBuilder.Entity("Hotel.models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Hotel.models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("statut")
                        .HasColumnType("int");

                    b.Property<int>("unClientId")
                        .HasColumnType("int");

                    b.Property<int>("uneChambreNumeroChambre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("unClientId");

                    b.HasIndex("uneChambreNumeroChambre");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Hotel.models.Reservation", b =>
                {
                    b.HasOne("Hotel.models.Client", "unClient")
                        .WithMany()
                        .HasForeignKey("unClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel.models.Chambre", "uneChambre")
                        .WithMany()
                        .HasForeignKey("uneChambreNumeroChambre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("unClient");

                    b.Navigation("uneChambre");
                });
#pragma warning restore 612, 618
        }
    }
}
